# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -m rregadmin.util.glib_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_info_wrapper -m rregadmin.util.ustring_wrapper -m rregadmin.util.offset_wrapper -m rregadmin.util.value_wrapper -m rregadmin.util.ustring_list_wrapper -m rregadmin.hive.types_wrapper -r ^hive_foreach_.* -o foreach_wrapper.py foreach_wrapper.xml'
from ctypes import *

from rregadmin.util.ustring_list_wrapper import gboolean
from rregadmin.hive.types_wrapper import Hive
from rregadmin.util.path_wrapper import rra_path
from rregadmin.hive.types_wrapper import KeyCell
from rregadmin.util.glib_wrapper import gpointer
_libraries = {}
_libraries['librregadmin.so.1'] = CDLL('librregadmin.so.1')
from rregadmin.hive.types_wrapper import ValueKeyCell


HiveForeachKeyFunc = CFUNCTYPE(gboolean, POINTER(KeyCell), POINTER(rra_path), gpointer)
# ../../../rregadmin/hive/foreach.h 47
hive_foreach_key = _libraries['librregadmin.so.1'].hive_foreach_key
hive_foreach_key.restype = gboolean
# hive_foreach_key(in_hive, in_start_path, in_func, in_data)
hive_foreach_key.argtypes = [POINTER(Hive), POINTER(rra_path), HiveForeachKeyFunc, gpointer]
hive_foreach_key.__doc__ = \
"""gboolean hive_foreach_key(Hive * in_hive, unknown * in_start_path, HiveForeachKeyFunc in_func, gpointer in_data)
../../../rregadmin/hive/foreach.h:47"""
HiveForeachValueFunc = CFUNCTYPE(gboolean, POINTER(KeyCell), POINTER(ValueKeyCell), POINTER(rra_path), gpointer)
# ../../../rregadmin/hive/foreach.h 65
hive_foreach_value = _libraries['librregadmin.so.1'].hive_foreach_value
hive_foreach_value.restype = gboolean
# hive_foreach_value(in_hive, in_start_path, in_func, in_data)
hive_foreach_value.argtypes = [POINTER(Hive), POINTER(rra_path), HiveForeachValueFunc, gpointer]
hive_foreach_value.__doc__ = \
"""gboolean hive_foreach_value(Hive * in_hive, unknown * in_start_path, HiveForeachValueFunc in_func, gpointer in_data)
../../../rregadmin/hive/foreach.h:65"""
__all__ = ['hive_foreach_key', 'hive_foreach_value',
           'HiveForeachKeyFunc', 'HiveForeachValueFunc']
