# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -m rregadmin.util.glib_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_info_wrapper -m rregadmin.util.ustring_wrapper -m rregadmin.util.offset_wrapper -m rregadmin.util.value_wrapper -m rregadmin.util.ustring_list_wrapper -m rregadmin.hive.types_wrapper -r ^hive_check -r ^HiveCheckVerbosity$ -o hive_check_wrapper.py hive_check_wrapper.xml'
from ctypes import *

from rregadmin.util.ustring_list_wrapper import gboolean
from rregadmin.hive.types_wrapper import Hive
_libraries = {}
_libraries['librregadmin.so.1'] = CDLL('librregadmin.so.1')
from rregadmin.hive.types_wrapper import guint32


# ../../../rregadmin/util/check.h 72
class RRACheckData_(Structure):
    pass
RRACheckData = RRACheckData_
# ../../../rregadmin/hive/hive_check.h 35
hive_check = _libraries['librregadmin.so.1'].hive_check
hive_check.restype = gboolean
# hive_check(in_hive, in_data)
hive_check.argtypes = [POINTER(Hive), POINTER(RRACheckData)]
hive_check.__doc__ = \
"""gboolean hive_check(Hive * in_hive, RRACheckData * in_data)
../../../rregadmin/hive/hive_check.h:35"""

# values for enumeration 'RRACheckVerbosity'
RRA_CHECK_VERBOSITY_QUIET = 0
RRA_CHECK_VERBOSITY_ERROR = 1
RRA_CHECK_VERBOSITY_WARNING = 2
RRA_CHECK_VERBOSITY_MESSAGE = 3
RRA_CHECK_VERBOSITY_INFO = 4
RRA_CHECK_VERBOSITY_DEBUG = 5
RRACheckVerbosity = c_int # enum
rra_check_flags = guint32
RRACheckData_._fields_ = [
    # ../../../rregadmin/util/check.h 72
    ('verbosity', RRACheckVerbosity),
    ('level', c_int),
    ('flags', rra_check_flags),
]
__all__ = ['RRA_CHECK_VERBOSITY_WARNING', 'RRACheckData_',
           'rra_check_flags', 'RRACheckVerbosity',
           'RRA_CHECK_VERBOSITY_ERROR', 'RRA_CHECK_VERBOSITY_INFO',
           'RRA_CHECK_VERBOSITY_MESSAGE', 'RRA_CHECK_VERBOSITY_DEBUG',
           'hive_check', 'RRA_CHECK_VERBOSITY_QUIET', 'RRACheckData']
