# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -r ^rra_hive_init.*$ -o init_wrapper.py init_wrapper.xml'
from ctypes import *

_libraries = {}
_libraries['librregadmin.so.1'] = CDLL('librregadmin.so.1')


# ../../../rregadmin/hive/init.h 42
rra_hive_init = _libraries['librregadmin.so.1'].rra_hive_init
rra_hive_init.restype = None
# rra_hive_init()
rra_hive_init.argtypes = []
rra_hive_init.__doc__ = \
"""void rra_hive_init()
../../../rregadmin/hive/init.h:42"""
# ../../../rregadmin/hive/init.h 48
rra_hive_init_from_env = _libraries['librregadmin.so.1'].rra_hive_init_from_env
rra_hive_init_from_env.restype = None
# rra_hive_init_from_env()
rra_hive_init_from_env.argtypes = []
rra_hive_init_from_env.__doc__ = \
"""void rra_hive_init_from_env()
../../../rregadmin/hive/init.h:48"""
__all__ = ['rra_hive_init_from_env', 'rra_hive_init']
