# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -m rregadmin.util.glib_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_info_wrapper -m rregadmin.util.ustring_wrapper -m rregadmin.util.offset_wrapper -m rregadmin.util.value_wrapper -m rregadmin.util.ustring_list_wrapper -m rregadmin.hive.types_wrapper -r ^key_cell_.* -o key_cell_wrapper.py key_cell_wrapper.xml'
from ctypes import *

from rregadmin.util.glib_wrapper import guint16
from rregadmin.hive.types_wrapper import KeyCell
from rregadmin.hive.types_wrapper import Hive
from rregadmin.util.offset_wrapper import offset
from rregadmin.util.ustring_list_wrapper import ustring
_libraries = {}
_libraries['librregadmin.so.1'] = CDLL('librregadmin.so.1')
from rregadmin.util.ustring_list_wrapper import gboolean
from rregadmin.hive.types_wrapper import Cell
STRING = c_char_p
from rregadmin.hive.types_wrapper import guint32
from rregadmin.hive.types_wrapper import ValueKeyCell
from rregadmin.util.value_wrapper import Value
from rregadmin.hive.types_wrapper import KeyListCell
from rregadmin.hive.types_wrapper import ValueListCell
from rregadmin.hive.types_wrapper import SecurityDescriptorCell
from rregadmin.hive.types_wrapper import ValueCell


key_cell_type = guint16
# ../../../rregadmin/hive/key_cell.h 83
key_cell_alloc = _libraries['librregadmin.so.1'].key_cell_alloc
key_cell_alloc.restype = POINTER(KeyCell)
# key_cell_alloc(in_hive, in_ofs, in_name)
key_cell_alloc.argtypes = [POINTER(Hive), offset, POINTER(ustring)]
key_cell_alloc.__doc__ = \
"""KeyCell * key_cell_alloc(Hive * in_hive, offset in_ofs, unknown * in_name)
../../../rregadmin/hive/key_cell.h:83"""
# ../../../rregadmin/hive/key_cell.h 89
key_cell_unalloc = _libraries['librregadmin.so.1'].key_cell_unalloc
key_cell_unalloc.restype = gboolean
# key_cell_unalloc(in_kc, in_recursive)
key_cell_unalloc.argtypes = [POINTER(KeyCell), gboolean]
key_cell_unalloc.__doc__ = \
"""gboolean key_cell_unalloc(KeyCell * in_kc, gboolean in_recursive)
../../../rregadmin/hive/key_cell.h:89"""
# ../../../rregadmin/hive/key_cell.h 98
key_cell_alloc_root = _libraries['librregadmin.so.1'].key_cell_alloc_root
key_cell_alloc_root.restype = POINTER(KeyCell)
# key_cell_alloc_root(in_hive)
key_cell_alloc_root.argtypes = [POINTER(Hive)]
key_cell_alloc_root.__doc__ = \
"""KeyCell * key_cell_alloc_root(Hive * in_hive)
../../../rregadmin/hive/key_cell.h:98"""
# ../../../rregadmin/hive/key_cell.h 104
key_cell_from_cell = _libraries['librregadmin.so.1'].key_cell_from_cell
key_cell_from_cell.restype = POINTER(KeyCell)
# key_cell_from_cell(in_cell)
key_cell_from_cell.argtypes = [POINTER(Cell)]
key_cell_from_cell.__doc__ = \
"""KeyCell * key_cell_from_cell(Cell * in_cell)
../../../rregadmin/hive/key_cell.h:104"""
# ../../../rregadmin/hive/key_cell.h 110
key_cell_to_cell = _libraries['librregadmin.so.1'].key_cell_to_cell
key_cell_to_cell.restype = POINTER(Cell)
# key_cell_to_cell(in_kc)
key_cell_to_cell.argtypes = [POINTER(KeyCell)]
key_cell_to_cell.__doc__ = \
"""Cell * key_cell_to_cell(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:110"""
# ../../../rregadmin/hive/key_cell.h 116
key_cell_is_valid = _libraries['librregadmin.so.1'].key_cell_is_valid
key_cell_is_valid.restype = gboolean
# key_cell_is_valid(in_kc)
key_cell_is_valid.argtypes = [POINTER(KeyCell)]
key_cell_is_valid.__doc__ = \
"""gboolean key_cell_is_valid(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:116"""
# ../../../rregadmin/hive/key_cell.h 122
key_cell_get_parent = _libraries['librregadmin.so.1'].key_cell_get_parent
key_cell_get_parent.restype = POINTER(KeyCell)
# key_cell_get_parent(in_kc)
key_cell_get_parent.argtypes = [POINTER(KeyCell)]
key_cell_get_parent.__doc__ = \
"""KeyCell * key_cell_get_parent(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:122"""
# ../../../rregadmin/hive/key_cell.h 130
key_cell_get_type_str = _libraries['librregadmin.so.1'].key_cell_get_type_str
key_cell_get_type_str.restype = STRING
# key_cell_get_type_str(in_kc)
key_cell_get_type_str.argtypes = [POINTER(KeyCell)]
key_cell_get_type_str.__doc__ = \
"""unknown * key_cell_get_type_str(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:130"""
# ../../../rregadmin/hive/key_cell.h 138
key_cell_get_type_id = _libraries['librregadmin.so.1'].key_cell_get_type_id
key_cell_get_type_id.restype = key_cell_type
# key_cell_get_type_id(in_kc)
key_cell_get_type_id.argtypes = [POINTER(KeyCell)]
key_cell_get_type_id.__doc__ = \
"""key_cell_type key_cell_get_type_id(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:138"""
# ../../../rregadmin/hive/key_cell.h 146
key_cell_get_name = _libraries['librregadmin.so.1'].key_cell_get_name
key_cell_get_name.restype = POINTER(ustring)
# key_cell_get_name(in_kc)
key_cell_get_name.argtypes = [POINTER(KeyCell)]
key_cell_get_name.__doc__ = \
"""ustring * key_cell_get_name(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:146"""
# ../../../rregadmin/hive/key_cell.h 154
key_cell_get_classname = _libraries['librregadmin.so.1'].key_cell_get_classname
key_cell_get_classname.restype = POINTER(ustring)
# key_cell_get_classname(in_kc)
key_cell_get_classname.argtypes = [POINTER(KeyCell)]
key_cell_get_classname.__doc__ = \
"""ustring * key_cell_get_classname(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:154"""
# ../../../rregadmin/hive/key_cell.h 160
key_cell_compare_names = _libraries['librregadmin.so.1'].key_cell_compare_names
key_cell_compare_names.restype = c_int
# key_cell_compare_names(in_kc1, in_kc2)
key_cell_compare_names.argtypes = [POINTER(KeyCell), POINTER(KeyCell)]
key_cell_compare_names.__doc__ = \
"""int key_cell_compare_names(KeyCell * in_kc1, KeyCell * in_kc2)
../../../rregadmin/hive/key_cell.h:160"""
# ../../../rregadmin/hive/key_cell.h 166
key_cell_get_number_of_values = _libraries['librregadmin.so.1'].key_cell_get_number_of_values
key_cell_get_number_of_values.restype = guint32
# key_cell_get_number_of_values(in_kc)
key_cell_get_number_of_values.argtypes = [POINTER(KeyCell)]
key_cell_get_number_of_values.__doc__ = \
"""guint32 key_cell_get_number_of_values(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:166"""
# ../../../rregadmin/hive/key_cell.h 172
key_cell_get_value = _libraries['librregadmin.so.1'].key_cell_get_value
key_cell_get_value.restype = POINTER(ValueKeyCell)
# key_cell_get_value(in_kc, in_index)
key_cell_get_value.argtypes = [POINTER(KeyCell), guint32]
key_cell_get_value.__doc__ = \
"""ValueKeyCell * key_cell_get_value(KeyCell * in_kc, guint32 in_index)
../../../rregadmin/hive/key_cell.h:172"""
# ../../../rregadmin/hive/key_cell.h 178
key_cell_get_value_str = _libraries['librregadmin.so.1'].key_cell_get_value_str
key_cell_get_value_str.restype = POINTER(ValueKeyCell)
# key_cell_get_value_str(in_kc, in_name)
key_cell_get_value_str.argtypes = [POINTER(KeyCell), STRING]
key_cell_get_value_str.__doc__ = \
"""ValueKeyCell * key_cell_get_value_str(KeyCell * in_kc, unknown * in_name)
../../../rregadmin/hive/key_cell.h:178"""
# ../../../rregadmin/hive/key_cell.h 184
key_cell_get_value_ustr = _libraries['librregadmin.so.1'].key_cell_get_value_ustr
key_cell_get_value_ustr.restype = POINTER(ValueKeyCell)
# key_cell_get_value_ustr(in_kc, in_name)
key_cell_get_value_ustr.argtypes = [POINTER(KeyCell), POINTER(ustring)]
key_cell_get_value_ustr.__doc__ = \
"""ValueKeyCell * key_cell_get_value_ustr(KeyCell * in_kc, unknown * in_name)
../../../rregadmin/hive/key_cell.h:184"""
# ../../../rregadmin/hive/key_cell.h 190
key_cell_delete_value = _libraries['librregadmin.so.1'].key_cell_delete_value
key_cell_delete_value.restype = gboolean
# key_cell_delete_value(in_kc, in_index)
key_cell_delete_value.argtypes = [POINTER(KeyCell), guint32]
key_cell_delete_value.__doc__ = \
"""gboolean key_cell_delete_value(KeyCell * in_kc, guint32 in_index)
../../../rregadmin/hive/key_cell.h:190"""
# ../../../rregadmin/hive/key_cell.h 196
key_cell_delete_value_str = _libraries['librregadmin.so.1'].key_cell_delete_value_str
key_cell_delete_value_str.restype = gboolean
# key_cell_delete_value_str(in_kc, in_name)
key_cell_delete_value_str.argtypes = [POINTER(KeyCell), STRING]
key_cell_delete_value_str.__doc__ = \
"""gboolean key_cell_delete_value_str(KeyCell * in_kc, unknown * in_name)
../../../rregadmin/hive/key_cell.h:196"""
# ../../../rregadmin/hive/key_cell.h 202
key_cell_delete_value_ustr = _libraries['librregadmin.so.1'].key_cell_delete_value_ustr
key_cell_delete_value_ustr.restype = gboolean
# key_cell_delete_value_ustr(in_kc, in_name)
key_cell_delete_value_ustr.argtypes = [POINTER(KeyCell), POINTER(ustring)]
key_cell_delete_value_ustr.__doc__ = \
"""gboolean key_cell_delete_value_ustr(KeyCell * in_kc, unknown * in_name)
../../../rregadmin/hive/key_cell.h:202"""
# ../../../rregadmin/hive/key_cell.h 209
key_cell_add_value = _libraries['librregadmin.so.1'].key_cell_add_value
key_cell_add_value.restype = POINTER(ValueKeyCell)
# key_cell_add_value(in_kc, in_name, in_val)
key_cell_add_value.argtypes = [POINTER(KeyCell), STRING, POINTER(Value)]
key_cell_add_value.__doc__ = \
"""ValueKeyCell * key_cell_add_value(KeyCell * in_kc, unknown * in_name, unknown * in_val)
../../../rregadmin/hive/key_cell.h:209"""
# ../../../rregadmin/hive/key_cell.h 222
key_cell_get_number_of_subkeys = _libraries['librregadmin.so.1'].key_cell_get_number_of_subkeys
key_cell_get_number_of_subkeys.restype = guint32
# key_cell_get_number_of_subkeys(in_kc)
key_cell_get_number_of_subkeys.argtypes = [POINTER(KeyCell)]
key_cell_get_number_of_subkeys.__doc__ = \
"""guint32 key_cell_get_number_of_subkeys(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:222"""
# ../../../rregadmin/hive/key_cell.h 228
key_cell_get_subkey = _libraries['librregadmin.so.1'].key_cell_get_subkey
key_cell_get_subkey.restype = POINTER(KeyCell)
# key_cell_get_subkey(in_kc, in_index)
key_cell_get_subkey.argtypes = [POINTER(KeyCell), guint32]
key_cell_get_subkey.__doc__ = \
"""KeyCell * key_cell_get_subkey(KeyCell * in_kc, guint32 in_index)
../../../rregadmin/hive/key_cell.h:228"""
# ../../../rregadmin/hive/key_cell.h 234
key_cell_get_subkey_str = _libraries['librregadmin.so.1'].key_cell_get_subkey_str
key_cell_get_subkey_str.restype = POINTER(KeyCell)
# key_cell_get_subkey_str(in_kc, in_name)
key_cell_get_subkey_str.argtypes = [POINTER(KeyCell), STRING]
key_cell_get_subkey_str.__doc__ = \
"""KeyCell * key_cell_get_subkey_str(KeyCell * in_kc, unknown * in_name)
../../../rregadmin/hive/key_cell.h:234"""
# ../../../rregadmin/hive/key_cell.h 240
key_cell_get_subkey_ustr = _libraries['librregadmin.so.1'].key_cell_get_subkey_ustr
key_cell_get_subkey_ustr.restype = POINTER(KeyCell)
# key_cell_get_subkey_ustr(in_kc, in_name)
key_cell_get_subkey_ustr.argtypes = [POINTER(KeyCell), POINTER(ustring)]
key_cell_get_subkey_ustr.__doc__ = \
"""KeyCell * key_cell_get_subkey_ustr(KeyCell * in_kc, unknown * in_name)
../../../rregadmin/hive/key_cell.h:240"""
# ../../../rregadmin/hive/key_cell.h 246
key_cell_delete_subkey = _libraries['librregadmin.so.1'].key_cell_delete_subkey
key_cell_delete_subkey.restype = gboolean
# key_cell_delete_subkey(in_kc, in_index)
key_cell_delete_subkey.argtypes = [POINTER(KeyCell), guint32]
key_cell_delete_subkey.__doc__ = \
"""gboolean key_cell_delete_subkey(KeyCell * in_kc, guint32 in_index)
../../../rregadmin/hive/key_cell.h:246"""
# ../../../rregadmin/hive/key_cell.h 252
key_cell_delete_subkey_str = _libraries['librregadmin.so.1'].key_cell_delete_subkey_str
key_cell_delete_subkey_str.restype = gboolean
# key_cell_delete_subkey_str(in_kc, in_name)
key_cell_delete_subkey_str.argtypes = [POINTER(KeyCell), STRING]
key_cell_delete_subkey_str.__doc__ = \
"""gboolean key_cell_delete_subkey_str(KeyCell * in_kc, unknown * in_name)
../../../rregadmin/hive/key_cell.h:252"""
# ../../../rregadmin/hive/key_cell.h 258
key_cell_delete_subkey_ustr = _libraries['librregadmin.so.1'].key_cell_delete_subkey_ustr
key_cell_delete_subkey_ustr.restype = gboolean
# key_cell_delete_subkey_ustr(in_kc, in_name)
key_cell_delete_subkey_ustr.argtypes = [POINTER(KeyCell), POINTER(ustring)]
key_cell_delete_subkey_ustr.__doc__ = \
"""gboolean key_cell_delete_subkey_ustr(KeyCell * in_kc, unknown * in_name)
../../../rregadmin/hive/key_cell.h:258"""
# ../../../rregadmin/hive/key_cell.h 264
key_cell_add_subkey = _libraries['librregadmin.so.1'].key_cell_add_subkey
key_cell_add_subkey.restype = POINTER(KeyCell)
# key_cell_add_subkey(in_kc, in_name)
key_cell_add_subkey.argtypes = [POINTER(KeyCell), POINTER(ustring)]
key_cell_add_subkey.__doc__ = \
"""KeyCell * key_cell_add_subkey(KeyCell * in_kc, unknown * in_name)
../../../rregadmin/hive/key_cell.h:264"""
# ../../../rregadmin/hive/key_cell.h 273
key_cell_set_key_list_cell = _libraries['librregadmin.so.1'].key_cell_set_key_list_cell
key_cell_set_key_list_cell.restype = gboolean
# key_cell_set_key_list_cell(in_kc, in_klc, in_recursive)
key_cell_set_key_list_cell.argtypes = [POINTER(KeyCell), POINTER(KeyListCell), gboolean]
key_cell_set_key_list_cell.__doc__ = \
"""gboolean key_cell_set_key_list_cell(KeyCell * in_kc, KeyListCell * in_klc, gboolean in_recursive)
../../../rregadmin/hive/key_cell.h:273"""
# ../../../rregadmin/hive/key_cell.h 281
key_cell_get_key_list_cell = _libraries['librregadmin.so.1'].key_cell_get_key_list_cell
key_cell_get_key_list_cell.restype = POINTER(KeyListCell)
# key_cell_get_key_list_cell(in_kc)
key_cell_get_key_list_cell.argtypes = [POINTER(KeyCell)]
key_cell_get_key_list_cell.__doc__ = \
"""KeyListCell * key_cell_get_key_list_cell(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:281"""
# ../../../rregadmin/hive/key_cell.h 289
key_cell_get_value_list_cell = _libraries['librregadmin.so.1'].key_cell_get_value_list_cell
key_cell_get_value_list_cell.restype = POINTER(ValueListCell)
# key_cell_get_value_list_cell(in_kc)
key_cell_get_value_list_cell.argtypes = [POINTER(KeyCell)]
key_cell_get_value_list_cell.__doc__ = \
"""ValueListCell * key_cell_get_value_list_cell(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:289"""
# ../../../rregadmin/hive/key_cell.h 297
key_cell_get_security_descriptor_cell = _libraries['librregadmin.so.1'].key_cell_get_security_descriptor_cell
key_cell_get_security_descriptor_cell.restype = POINTER(SecurityDescriptorCell)
# key_cell_get_security_descriptor_cell(in_kc)
key_cell_get_security_descriptor_cell.argtypes = [POINTER(KeyCell)]
key_cell_get_security_descriptor_cell.__doc__ = \
"""SecurityDescriptorCell * key_cell_get_security_descriptor_cell(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:297"""
# ../../../rregadmin/secdesc/security_descriptor.h 62
class SecurityDescriptor_(Structure):
    pass
SecurityDescriptor = SecurityDescriptor_
# ../../../rregadmin/hive/key_cell.h 303
key_cell_get_secdesc = _libraries['librregadmin.so.1'].key_cell_get_secdesc
key_cell_get_secdesc.restype = POINTER(SecurityDescriptor)
# key_cell_get_secdesc(in_kc)
key_cell_get_secdesc.argtypes = [POINTER(KeyCell)]
key_cell_get_secdesc.__doc__ = \
"""unknown * key_cell_get_secdesc(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:303"""
# ../../../rregadmin/hive/key_cell.h 310
key_cell_set_secdesc = _libraries['librregadmin.so.1'].key_cell_set_secdesc
key_cell_set_secdesc.restype = gboolean
# key_cell_set_secdesc(in_kc, in_secdesc)
key_cell_set_secdesc.argtypes = [POINTER(KeyCell), POINTER(SecurityDescriptor)]
key_cell_set_secdesc.__doc__ = \
"""gboolean key_cell_set_secdesc(KeyCell * in_kc, unknown * in_secdesc)
../../../rregadmin/hive/key_cell.h:310"""
# ../../../rregadmin/hive/key_cell.h 318
key_cell_get_classname_value_cell = _libraries['librregadmin.so.1'].key_cell_get_classname_value_cell
key_cell_get_classname_value_cell.restype = POINTER(ValueCell)
# key_cell_get_classname_value_cell(in_kc)
key_cell_get_classname_value_cell.argtypes = [POINTER(KeyCell)]
key_cell_get_classname_value_cell.__doc__ = \
"""ValueCell * key_cell_get_classname_value_cell(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:318"""
# ../../../rregadmin/hive/key_cell.h 326
key_cell_debug_print = _libraries['librregadmin.so.1'].key_cell_debug_print
key_cell_debug_print.restype = None
# key_cell_debug_print(in_kc)
key_cell_debug_print.argtypes = [POINTER(KeyCell)]
key_cell_debug_print.__doc__ = \
"""void key_cell_debug_print(KeyCell * in_kc)
../../../rregadmin/hive/key_cell.h:326"""
# ../../../rregadmin/hive/key_cell.h 334
key_cell_pretty_print = _libraries['librregadmin.so.1'].key_cell_pretty_print
key_cell_pretty_print.restype = None
# key_cell_pretty_print(in_kc, in_pathname)
key_cell_pretty_print.argtypes = [POINTER(KeyCell), STRING]
key_cell_pretty_print.__doc__ = \
"""void key_cell_pretty_print(KeyCell * in_kc, unknown * in_pathname)
../../../rregadmin/hive/key_cell.h:334"""
# ../../../rregadmin/hive/key_cell.h 341
key_cell_get_pretty_output = _libraries['librregadmin.so.1'].key_cell_get_pretty_output
key_cell_get_pretty_output.restype = gboolean
# key_cell_get_pretty_output(in_kc, in_pathname, in_output)
key_cell_get_pretty_output.argtypes = [POINTER(KeyCell), STRING, POINTER(ustring)]
key_cell_get_pretty_output.__doc__ = \
"""gboolean key_cell_get_pretty_output(KeyCell * in_kc, unknown * in_pathname, ustring * in_output)
../../../rregadmin/hive/key_cell.h:341"""
# ../../../rregadmin/hive/key_cell.h 347
key_cell_get_xml_output = _libraries['librregadmin.so.1'].key_cell_get_xml_output
key_cell_get_xml_output.restype = gboolean
# key_cell_get_xml_output(in_kc, in_output)
key_cell_get_xml_output.argtypes = [POINTER(KeyCell), POINTER(ustring)]
key_cell_get_xml_output.__doc__ = \
"""gboolean key_cell_get_xml_output(KeyCell * in_kc, ustring * in_output)
../../../rregadmin/hive/key_cell.h:347"""
# ../../../rregadmin/hive/key_cell.h 355
key_cell_get_parseable_output = _libraries['librregadmin.so.1'].key_cell_get_parseable_output
key_cell_get_parseable_output.restype = gboolean
# key_cell_get_parseable_output(in_kc, in_pathname, in_output)
key_cell_get_parseable_output.argtypes = [POINTER(KeyCell), STRING, POINTER(ustring)]
key_cell_get_parseable_output.__doc__ = \
"""gboolean key_cell_get_parseable_output(KeyCell * in_kc, unknown * in_pathname, ustring * in_output)
../../../rregadmin/hive/key_cell.h:355"""
SecurityDescriptor_._fields_ = [
    # ../../../rregadmin/secdesc/security_descriptor.h 62
]
__all__ = ['key_cell_get_secdesc', 'key_cell_get_subkey_str',
           'key_cell_get_value_str', 'key_cell_get_value_list_cell',
           'key_cell_alloc_root', 'key_cell_get_value_ustr',
           'key_cell_set_secdesc', 'key_cell_get_number_of_subkeys',
           'SecurityDescriptor_', 'key_cell_get_type_id',
           'key_cell_get_subkey_ustr',
           'key_cell_get_parseable_output', 'SecurityDescriptor',
           'key_cell_get_classname_value_cell',
           'key_cell_get_pretty_output', 'key_cell_get_classname',
           'key_cell_get_number_of_values',
           'key_cell_get_key_list_cell', 'key_cell_debug_print',
           'key_cell_type', 'key_cell_delete_subkey_ustr',
           'key_cell_get_name', 'key_cell_add_subkey',
           'key_cell_alloc', 'key_cell_delete_value_str',
           'key_cell_pretty_print', 'key_cell_add_value',
           'key_cell_unalloc', 'key_cell_delete_value_ustr',
           'key_cell_from_cell', 'key_cell_set_key_list_cell',
           'key_cell_get_type_str', 'key_cell_get_subkey',
           'key_cell_get_value', 'key_cell_to_cell',
           'key_cell_delete_subkey', 'key_cell_is_valid',
           'key_cell_get_parent',
           'key_cell_get_security_descriptor_cell',
           'key_cell_get_xml_output', 'key_cell_compare_names',
           'key_cell_delete_subkey_str', 'key_cell_delete_value']
