# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -m rregadmin.util.glib_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_info_wrapper -m rregadmin.util.ustring_wrapper -m rregadmin.util.offset_wrapper -m rregadmin.util.value_wrapper -m rregadmin.util.ustring_list_wrapper -r HiveVersion -r Hive -r Bin -r Cell -r used_stats -r SecurityDescriptorCell -r KeyCell -r ValueKeyCell -r KeyListCell -r ValueListCell -r ValueCell -o types_wrapper.py types_wrapper.xml'
from ctypes import *

from rregadmin.util.value_wrapper import guint32


# ../../../rregadmin/hive/types.h 51
class HiveVersion_(Structure):
    pass
HiveVersion = HiveVersion_
# ../../../rregadmin/hive/types.h 73
class Hive_(Structure):
    pass
Hive = Hive_
# ../../../rregadmin/hive/types.h 75
class Bin_(Structure):
    pass
Bin = Bin_
# ../../../rregadmin/hive/types.h 77
class Cell_(Structure):
    pass
Cell = Cell_
# ../../../rregadmin/hive/types.h 82
class used_stats(Structure):
    pass
used_stats._fields_ = [
    # ../../../rregadmin/hive/types.h 82
    ('blocks', guint32),
    ('keys', guint32),
    ('values', guint32),
    ('used', guint32),
    ('free', guint32),
    ('data', guint32),
    ('lost', guint32),
]
# ../../../rregadmin/hive/types.h 109
class SecurityDescriptorCell_(Structure):
    pass
SecurityDescriptorCell = SecurityDescriptorCell_
# ../../../rregadmin/hive/types.h 111
class KeyCell_(Structure):
    pass
KeyCell = KeyCell_
# ../../../rregadmin/hive/types.h 113
class ValueKeyCell_(Structure):
    pass
ValueKeyCell = ValueKeyCell_
# ../../../rregadmin/hive/types.h 115
class KeyListCell_(Structure):
    pass
KeyListCell = KeyListCell_
# ../../../rregadmin/hive/types.h 117
class ValueListCell_(Structure):
    pass
ValueListCell = ValueListCell_
# ../../../rregadmin/hive/types.h 119
class ValueCell_(Structure):
    pass
ValueCell = ValueCell_
HiveVersion_._pack_ = 1
HiveVersion_._fields_ = [
    # ../../../rregadmin/hive/types.h 51
    ('major', guint32),
    ('minor', guint32),
    ('release', guint32),
    ('build', guint32),
]
Hive_._fields_ = [
    # ../../../rregadmin/hive/types.h 73
]
Bin_._fields_ = [
    # ../../../rregadmin/hive/types.h 75
]
Cell_._fields_ = [
    # ../../../rregadmin/hive/types.h 77
]
SecurityDescriptorCell_._fields_ = [
    # ../../../rregadmin/hive/types.h 109
]
KeyCell_._fields_ = [
    # ../../../rregadmin/hive/types.h 111
]
ValueKeyCell_._fields_ = [
    # ../../../rregadmin/hive/types.h 113
]
KeyListCell_._fields_ = [
    # ../../../rregadmin/hive/types.h 115
]
ValueListCell_._fields_ = [
    # ../../../rregadmin/hive/types.h 117
]
ValueCell_._fields_ = [
    # ../../../rregadmin/hive/types.h 119
]
__all__ = ['Bin', 'HiveVersion_', 'ValueKeyCell', 'Hive_',
           'ValueKeyCell_', 'Cell_', 'ValueCell',
           'SecurityDescriptorCell', 'ValueListCell_', 'HiveVersion',
           'Hive', 'used_stats', 'Cell', 'Bin_', 'KeyListCell',
           'KeyCell', 'KeyListCell_', 'KeyCell_', 'ValueListCell',
           'ValueCell_', 'SecurityDescriptorCell_']
