# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -r ^rra_registry_init.*$ -o init_wrapper.py init_wrapper.xml'
from ctypes import *

_libraries = {}
_libraries['librregadmin.so.1'] = CDLL('librregadmin.so.1')


# ../../../rregadmin/registry/init.h 42
rra_registry_init = _libraries['librregadmin.so.1'].rra_registry_init
rra_registry_init.restype = None
# rra_registry_init()
rra_registry_init.argtypes = []
rra_registry_init.__doc__ = \
"""void rra_registry_init()
../../../rregadmin/registry/init.h:42"""
# ../../../rregadmin/registry/init.h 48
rra_registry_init_from_env = _libraries['librregadmin.so.1'].rra_registry_init_from_env
rra_registry_init_from_env.restype = None
# rra_registry_init_from_env()
rra_registry_init_from_env.argtypes = []
rra_registry_init_from_env.__doc__ = \
"""void rra_registry_init_from_env()
../../../rregadmin/registry/init.h:48"""
__all__ = ['rra_registry_init_from_env', 'rra_registry_init']
