# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -m rregadmin.util.glib_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_info_wrapper -m rregadmin.util.ustring_wrapper -m rregadmin.util.offset_wrapper -m rregadmin.util.value_wrapper -m rregadmin.util.ustring_list_wrapper -m rregadmin.hive.types_wrapper -m rregadmin.registry.types_wrapper -r ^ID_HKEY.* -r ^registry_.* -o registry_wrapper.py registry_wrapper.xml'
from ctypes import *

from rregadmin.registry.types_wrapper import Registry
_libraries = {}
_libraries['librregadmin.so.1'] = CDLL('librregadmin.so.1')
STRING = c_char_p
from rregadmin.util.ustring_list_wrapper import gboolean
from rregadmin.registry.types_wrapper import hive_id
from rregadmin.registry.types_wrapper import RegistryKey
from rregadmin.registry.types_wrapper import reg_id
from rregadmin.hive.types_wrapper import KeyCell
from rregadmin.hive.types_wrapper import ValueKeyCell
from rregadmin.util.value_wrapper import Value
from rregadmin.util.offset_wrapper import gint
from rregadmin.registry.types_wrapper import hive_info
from rregadmin.hive.types_wrapper import Hive
from rregadmin.util.ustring_list_wrapper import ustring


# ../../../rregadmin/registry/registry.h 95
registry_new = _libraries['librregadmin.so.1'].registry_new
registry_new.restype = POINTER(Registry)
# registry_new()
registry_new.argtypes = []
registry_new.__doc__ = \
"""Registry * registry_new()
../../../rregadmin/registry/registry.h:95"""
# ../../../rregadmin/registry/registry.h 104
registry_new_win_dir = _libraries['librregadmin.so.1'].registry_new_win_dir
registry_new_win_dir.restype = POINTER(Registry)
# registry_new_win_dir(in_dir)
registry_new_win_dir.argtypes = [STRING]
registry_new_win_dir.__doc__ = \
"""Registry * registry_new_win_dir(unknown * in_dir)
../../../rregadmin/registry/registry.h:104"""
# ../../../rregadmin/registry/registry.h 110
registry_free = _libraries['librregadmin.so.1'].registry_free
registry_free.restype = gboolean
# registry_free(in_reg)
registry_free.argtypes = [POINTER(Registry)]
registry_free.__doc__ = \
"""gboolean registry_free(Registry * in_reg)
../../../rregadmin/registry/registry.h:110"""
# ../../../rregadmin/registry/registry.h 126
registry_load_win_dir = _libraries['librregadmin.so.1'].registry_load_win_dir
registry_load_win_dir.restype = gboolean
# registry_load_win_dir(in_reg, in_dir)
registry_load_win_dir.argtypes = [POINTER(Registry), STRING]
registry_load_win_dir.__doc__ = \
"""gboolean registry_load_win_dir(Registry * in_reg, unknown * in_dir)
../../../rregadmin/registry/registry.h:126"""
# ../../../rregadmin/registry/registry.h 134
registry_load_hive = _libraries['librregadmin.so.1'].registry_load_hive
registry_load_hive.restype = hive_id
# registry_load_hive(in_reg, in_filename)
registry_load_hive.argtypes = [POINTER(Registry), STRING]
registry_load_hive.__doc__ = \
"""hive_id registry_load_hive(Registry * in_reg, unknown * in_filename)
../../../rregadmin/registry/registry.h:134"""
# ../../../rregadmin/registry/registry.h 141
registry_load_hive_full = _libraries['librregadmin.so.1'].registry_load_hive_full
registry_load_hive_full.restype = hive_id
# registry_load_hive_full(in_reg, in_filename, in_mount_point)
registry_load_hive_full.argtypes = [POINTER(Registry), STRING, STRING]
registry_load_hive_full.__doc__ = \
"""hive_id registry_load_hive_full(Registry * in_reg, unknown * in_filename, unknown * in_mount_point)
../../../rregadmin/registry/registry.h:141"""
# ../../../rregadmin/registry/registry.h 149
registry_unload = _libraries['librregadmin.so.1'].registry_unload
registry_unload.restype = gboolean
# registry_unload(in_reg, in_id)
registry_unload.argtypes = [POINTER(Registry), hive_id]
registry_unload.__doc__ = \
"""gboolean registry_unload(Registry * in_reg, hive_id in_id)
../../../rregadmin/registry/registry.h:149"""
# ../../../rregadmin/registry/registry.h 157
registry_unload_all = _libraries['librregadmin.so.1'].registry_unload_all
registry_unload_all.restype = gboolean
# registry_unload_all(in_reg)
registry_unload_all.argtypes = [POINTER(Registry)]
registry_unload_all.__doc__ = \
"""gboolean registry_unload_all(Registry * in_reg)
../../../rregadmin/registry/registry.h:157"""
# ../../../rregadmin/registry/registry.h 163
registry_unload_all_force = _libraries['librregadmin.so.1'].registry_unload_all_force
registry_unload_all_force.restype = gboolean
# registry_unload_all_force(in_reg)
registry_unload_all_force.argtypes = [POINTER(Registry)]
registry_unload_all_force.__doc__ = \
"""gboolean registry_unload_all_force(Registry * in_reg)
../../../rregadmin/registry/registry.h:163"""
# ../../../rregadmin/registry/registry.h 171
registry_flush_all = _libraries['librregadmin.so.1'].registry_flush_all
registry_flush_all.restype = gboolean
# registry_flush_all(in_reg)
registry_flush_all.argtypes = [POINTER(Registry)]
registry_flush_all.__doc__ = \
"""gboolean registry_flush_all(Registry * in_reg)
../../../rregadmin/registry/registry.h:171"""
# ../../../rregadmin/registry/registry.h 177
registry_flush = _libraries['librregadmin.so.1'].registry_flush
registry_flush.restype = gboolean
# registry_flush(in_reg, in_id)
registry_flush.argtypes = [POINTER(Registry), hive_id]
registry_flush.__doc__ = \
"""gboolean registry_flush(Registry * in_reg, hive_id in_id)
../../../rregadmin/registry/registry.h:177"""

# values for enumeration 'RegistryOption'
REG_OPT_BACKUP = 1
REG_OPT_CHECK_HIVES_READ = 2
REG_OPT_CHECK_HIVES_WRITE = 4
REG_OPT_CHECK_HIVES = 6
RegistryOption = c_int # enum
# ../../../rregadmin/registry/registry.h 199
registry_set_option = _libraries['librregadmin.so.1'].registry_set_option
registry_set_option.restype = gboolean
# registry_set_option(in_reg, in_opt)
registry_set_option.argtypes = [POINTER(Registry), RegistryOption]
registry_set_option.__doc__ = \
"""gboolean registry_set_option(Registry * in_reg, RegistryOption in_opt)
../../../rregadmin/registry/registry.h:199"""
# ../../../rregadmin/registry/registry.h 207
registry_unset_option = _libraries['librregadmin.so.1'].registry_unset_option
registry_unset_option.restype = gboolean
# registry_unset_option(in_reg, in_opt)
registry_unset_option.argtypes = [POINTER(Registry), RegistryOption]
registry_unset_option.__doc__ = \
"""gboolean registry_unset_option(Registry * in_reg, RegistryOption in_opt)
../../../rregadmin/registry/registry.h:207"""
# ../../../rregadmin/registry/registry.h 215
registry_has_option = _libraries['librregadmin.so.1'].registry_has_option
registry_has_option.restype = gboolean
# registry_has_option(in_reg, in_opt)
registry_has_option.argtypes = [POINTER(Registry), RegistryOption]
registry_has_option.__doc__ = \
"""gboolean registry_has_option(unknown * in_reg, RegistryOption in_opt)
../../../rregadmin/registry/registry.h:215"""
# ../../../rregadmin/registry/registry.h 222
registry_get_registry_key = _libraries['librregadmin.so.1'].registry_get_registry_key
registry_get_registry_key.restype = POINTER(RegistryKey)
# registry_get_registry_key(in_reg, in_id)
registry_get_registry_key.argtypes = [POINTER(Registry), reg_id]
registry_get_registry_key.__doc__ = \
"""unknown * registry_get_registry_key(unknown * in_reg, reg_id in_id)
../../../rregadmin/registry/registry.h:222"""
# ../../../rregadmin/registry/registry.h 229
registry_find_registry_key = _libraries['librregadmin.so.1'].registry_find_registry_key
registry_find_registry_key.restype = POINTER(RegistryKey)
# registry_find_registry_key(in_reg, in_path)
registry_find_registry_key.argtypes = [POINTER(Registry), STRING]
registry_find_registry_key.__doc__ = \
"""unknown * registry_find_registry_key(unknown * in_reg, unknown * in_path)
../../../rregadmin/registry/registry.h:229"""
# ../../../rregadmin/registry/registry.h 235
registry_path_is_key = _libraries['librregadmin.so.1'].registry_path_is_key
registry_path_is_key.restype = gboolean
# registry_path_is_key(in_reg, in_path)
registry_path_is_key.argtypes = [POINTER(Registry), STRING]
registry_path_is_key.__doc__ = \
"""gboolean registry_path_is_key(unknown * in_reg, unknown * in_path)
../../../rregadmin/registry/registry.h:235"""
# ../../../rregadmin/registry/registry.h 241
registry_path_get_key = _libraries['librregadmin.so.1'].registry_path_get_key
registry_path_get_key.restype = POINTER(KeyCell)
# registry_path_get_key(in_reg, in_path)
registry_path_get_key.argtypes = [POINTER(Registry), STRING]
registry_path_get_key.__doc__ = \
"""KeyCell * registry_path_get_key(unknown * in_reg, unknown * in_path)
../../../rregadmin/registry/registry.h:241"""
# ../../../rregadmin/registry/registry.h 247
registry_path_add_key = _libraries['librregadmin.so.1'].registry_path_add_key
registry_path_add_key.restype = POINTER(KeyCell)
# registry_path_add_key(in_reg, in_path)
registry_path_add_key.argtypes = [POINTER(Registry), STRING]
registry_path_add_key.__doc__ = \
"""KeyCell * registry_path_add_key(unknown * in_reg, unknown * in_path)
../../../rregadmin/registry/registry.h:247"""
# ../../../rregadmin/registry/registry.h 253
registry_path_delete_key = _libraries['librregadmin.so.1'].registry_path_delete_key
registry_path_delete_key.restype = gboolean
# registry_path_delete_key(in_reg, in_path)
registry_path_delete_key.argtypes = [POINTER(Registry), STRING]
registry_path_delete_key.__doc__ = \
"""gboolean registry_path_delete_key(unknown * in_reg, unknown * in_path)
../../../rregadmin/registry/registry.h:253"""
# ../../../rregadmin/registry/registry.h 260
registry_path_is_deletable_key = _libraries['librregadmin.so.1'].registry_path_is_deletable_key
registry_path_is_deletable_key.restype = gboolean
# registry_path_is_deletable_key(in_reg, in_path)
registry_path_is_deletable_key.argtypes = [POINTER(Registry), STRING]
registry_path_is_deletable_key.__doc__ = \
"""gboolean registry_path_is_deletable_key(unknown * in_reg, unknown * in_path)
../../../rregadmin/registry/registry.h:260"""
# ../../../rregadmin/registry/registry.h 268
registry_path_is_value = _libraries['librregadmin.so.1'].registry_path_is_value
registry_path_is_value.restype = gboolean
# registry_path_is_value(in_reg, in_path, in_value_name)
registry_path_is_value.argtypes = [POINTER(Registry), STRING, STRING]
registry_path_is_value.__doc__ = \
"""gboolean registry_path_is_value(unknown * in_reg, unknown * in_path, unknown * in_value_name)
../../../rregadmin/registry/registry.h:268"""
# ../../../rregadmin/registry/registry.h 276
registry_path_get_value = _libraries['librregadmin.so.1'].registry_path_get_value
registry_path_get_value.restype = POINTER(ValueKeyCell)
# registry_path_get_value(in_reg, in_path, in_value_name)
registry_path_get_value.argtypes = [POINTER(Registry), STRING, STRING]
registry_path_get_value.__doc__ = \
"""ValueKeyCell * registry_path_get_value(unknown * in_reg, unknown * in_path, unknown * in_value_name)
../../../rregadmin/registry/registry.h:276"""
# ../../../rregadmin/registry/registry.h 285
registry_path_add_value = _libraries['librregadmin.so.1'].registry_path_add_value
registry_path_add_value.restype = POINTER(ValueKeyCell)
# registry_path_add_value(in_reg, in_path, in_value_name, in_val)
registry_path_add_value.argtypes = [POINTER(Registry), STRING, STRING, POINTER(Value)]
registry_path_add_value.__doc__ = \
"""ValueKeyCell * registry_path_add_value(unknown * in_reg, unknown * in_path, unknown * in_value_name, unknown * in_val)
../../../rregadmin/registry/registry.h:285"""
# ../../../rregadmin/registry/registry.h 293
registry_path_delete_value = _libraries['librregadmin.so.1'].registry_path_delete_value
registry_path_delete_value.restype = gboolean
# registry_path_delete_value(in_reg, in_path, in_value_name)
registry_path_delete_value.argtypes = [POINTER(Registry), STRING, STRING]
registry_path_delete_value.__doc__ = \
"""gboolean registry_path_delete_value(unknown * in_reg, unknown * in_path, unknown * in_value_name)
../../../rregadmin/registry/registry.h:293"""
# ../../../rregadmin/registry/registry.h 299
registry_number_of_hives = _libraries['librregadmin.so.1'].registry_number_of_hives
registry_number_of_hives.restype = gint
# registry_number_of_hives(in_reg)
registry_number_of_hives.argtypes = [POINTER(Registry)]
registry_number_of_hives.__doc__ = \
"""gint registry_number_of_hives(unknown * in_reg)
../../../rregadmin/registry/registry.h:299"""
# ../../../rregadmin/registry/registry.h 305
registry_is_dirty = _libraries['librregadmin.so.1'].registry_is_dirty
registry_is_dirty.restype = gboolean
# registry_is_dirty(in_reg)
registry_is_dirty.argtypes = [POINTER(Registry)]
registry_is_dirty.__doc__ = \
"""gboolean registry_is_dirty(unknown * in_reg)
../../../rregadmin/registry/registry.h:305"""
# ../../../rregadmin/registry/registry.h 311
registry_set_dirty = _libraries['librregadmin.so.1'].registry_set_dirty
registry_set_dirty.restype = gboolean
# registry_set_dirty(in_reg, in_value)
registry_set_dirty.argtypes = [POINTER(Registry), gboolean]
registry_set_dirty.__doc__ = \
"""gboolean registry_set_dirty(Registry * in_reg, gboolean in_value)
../../../rregadmin/registry/registry.h:311"""
# ../../../rregadmin/registry/registry.h 317
registry_get_hive_info = _libraries['librregadmin.so.1'].registry_get_hive_info
registry_get_hive_info.restype = POINTER(hive_info)
# registry_get_hive_info(in_reg, in_id)
registry_get_hive_info.argtypes = [POINTER(Registry), hive_id]
registry_get_hive_info.__doc__ = \
"""unknown * registry_get_hive_info(unknown * in_reg, hive_id in_id)
../../../rregadmin/registry/registry.h:317"""

# values for enumeration 'HiveType'
HTYPE_UNKNOWN = 0
HTYPE_SAM = 1
HTYPE_SYSTEM = 2
HTYPE_SECURITY = 3
HTYPE_SOFTWARE = 4
HTYPE_USER = 5
HTYPE_USERDIFF = 6
HTYPE_USRCLASS = 7
HTYPE_DEFAULT = 8
HTYPE_UNLOADED = -1
HTYPE_ERROR = -2
HiveType = c_int # enum
# ../../../rregadmin/registry/registry.h 324
registry_contains_hivetype = _libraries['librregadmin.so.1'].registry_contains_hivetype
registry_contains_hivetype.restype = gboolean
# registry_contains_hivetype(in_reg, in_type)
registry_contains_hivetype.argtypes = [POINTER(Registry), HiveType]
registry_contains_hivetype.__doc__ = \
"""gboolean registry_contains_hivetype(unknown * in_reg, HiveType in_type)
../../../rregadmin/registry/registry.h:324"""
# ../../../rregadmin/registry/registry.h 330
registry_id_get_hive = _libraries['librregadmin.so.1'].registry_id_get_hive
registry_id_get_hive.restype = POINTER(Hive)
# registry_id_get_hive(in_reg, in_id)
registry_id_get_hive.argtypes = [POINTER(Registry), hive_id]
registry_id_get_hive.__doc__ = \
"""Hive * registry_id_get_hive(unknown * in_reg, hive_id in_id)
../../../rregadmin/registry/registry.h:330"""
# ../../../rregadmin/registry/registry.h 336
registry_id_get_hive_type = _libraries['librregadmin.so.1'].registry_id_get_hive_type
registry_id_get_hive_type.restype = c_int
# registry_id_get_hive_type(in_reg, in_id)
registry_id_get_hive_type.argtypes = [POINTER(Registry), hive_id]
registry_id_get_hive_type.__doc__ = \
"""int registry_id_get_hive_type(unknown * in_reg, hive_id in_id)
../../../rregadmin/registry/registry.h:336"""
# ../../../rregadmin/registry/registry.h 343
registry_id_get_hive_filename = _libraries['librregadmin.so.1'].registry_id_get_hive_filename
registry_id_get_hive_filename.restype = STRING
# registry_id_get_hive_filename(in_reg, in_id)
registry_id_get_hive_filename.argtypes = [POINTER(Registry), hive_id]
registry_id_get_hive_filename.__doc__ = \
"""unknown * registry_id_get_hive_filename(unknown * in_reg, hive_id in_id)
../../../rregadmin/registry/registry.h:343"""
# ../../../rregadmin/registry/registry.h 349
registry_get_xml_output = _libraries['librregadmin.so.1'].registry_get_xml_output
registry_get_xml_output.restype = gboolean
# registry_get_xml_output(in_reg, in_output)
registry_get_xml_output.argtypes = [POINTER(Registry), POINTER(ustring)]
registry_get_xml_output.__doc__ = \
"""gboolean registry_get_xml_output(unknown * in_reg, ustring * in_output)
../../../rregadmin/registry/registry.h:349"""
# ../../../rregadmin/registry/registry.h 358
registry_get_base_registry_key = _libraries['librregadmin.so.1'].registry_get_base_registry_key
registry_get_base_registry_key.restype = POINTER(RegistryKey)
# registry_get_base_registry_key(in_reg, in_id)
registry_get_base_registry_key.argtypes = [POINTER(Registry), hive_id]
registry_get_base_registry_key.__doc__ = \
"""unknown * registry_get_base_registry_key(unknown * in_reg, hive_id in_id)
../../../rregadmin/registry/registry.h:358"""
__all__ = ['registry_flush_all', 'HTYPE_SYSTEM',
           'registry_get_hive_info', 'registry_path_is_deletable_key',
           'registry_load_hive', 'RegistryOption', 'HTYPE_USRCLASS',
           'registry_unload_all_force', 'registry_get_xml_output',
           'registry_path_add_key', 'registry_unload_all',
           'HTYPE_UNLOADED', 'registry_unset_option',
           'registry_id_get_hive_type', 'registry_set_option',
           'HiveType', 'registry_flush', 'HTYPE_SOFTWARE',
           'registry_path_is_value', 'registry_has_option',
           'registry_path_delete_value', 'registry_new',
           'HTYPE_DEFAULT', 'registry_is_dirty',
           'registry_path_get_key', 'registry_unload',
           'REG_OPT_BACKUP', 'registry_path_add_value',
           'REG_OPT_CHECK_HIVES', 'registry_set_dirty', 'HTYPE_SAM',
           'REG_OPT_CHECK_HIVES_WRITE', 'registry_path_delete_key',
           'HTYPE_USER', 'registry_new_win_dir',
           'registry_number_of_hives', 'registry_load_win_dir',
           'registry_path_is_key', 'HTYPE_ERROR',
           'registry_id_get_hive', 'registry_get_base_registry_key',
           'registry_free', 'HTYPE_USERDIFF', 'HTYPE_UNKNOWN',
           'REG_OPT_CHECK_HIVES_READ', 'HTYPE_SECURITY',
           'registry_load_hive_full', 'registry_get_registry_key',
           'registry_contains_hivetype',
           'registry_id_get_hive_filename',
           'registry_find_registry_key', 'registry_path_get_value']
