# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -m rregadmin.util.glib_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_info_wrapper -m rregadmin.util.ustring_wrapper -m rregadmin.util.offset_wrapper -m rregadmin.util.value_wrapper -m rregadmin.util.ustring_list_wrapper -m rregadmin.hive.types_wrapper -r ^Registry -r ^RegistryKey -r ^hive_info -r ^reg_id$ -r ^hive_id$ -r ^hive_type$ -r ^reg_key_type$ -o types_wrapper.py types_wrapper.xml'
from ctypes import *

from rregadmin.util.offset_wrapper import gint32


# ../../../rregadmin/registry/types.h 34
class RegistryKey_(Structure):
    pass
RegistryKey = RegistryKey_
# ../../../rregadmin/registry/types.h 36
class Registry_(Structure):
    pass
Registry = Registry_
# ../../../rregadmin/registry/types.h 38
class hive_info_(Structure):
    pass
hive_info = hive_info_
reg_id = gint32
hive_id = gint32
RegistryKey_._fields_ = [
    # ../../../rregadmin/registry/types.h 34
]
Registry_._fields_ = [
    # ../../../rregadmin/registry/types.h 36
]
hive_info_._fields_ = [
    # ../../../rregadmin/registry/types.h 38
]
__all__ = ['RegistryKey', 'hive_info', 'Registry_', 'RegistryKey_',
           'reg_id', 'hive_info_', 'Registry', 'hive_id']
