# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -r ^rra_util_init.*$ -o init_wrapper.py init_wrapper.xml'
from ctypes import *

_libraries = {}
_libraries['librregadmin.so.1'] = CDLL('librregadmin.so.1')


# ../../../rregadmin/util/init.h 39
rra_util_init = _libraries['librregadmin.so.1'].rra_util_init
rra_util_init.restype = None
# rra_util_init()
rra_util_init.argtypes = []
rra_util_init.__doc__ = \
"""void rra_util_init()
../../../rregadmin/util/init.h:39"""
# ../../../rregadmin/util/init.h 45
rra_util_init_from_env = _libraries['librregadmin.so.1'].rra_util_init_from_env
rra_util_init_from_env.restype = None
# rra_util_init_from_env()
rra_util_init_from_env.argtypes = []
rra_util_init_from_env.__doc__ = \
"""void rra_util_init_from_env()
../../../rregadmin/util/init.h:45"""
__all__ = ['rra_util_init', 'rra_util_init_from_env']
