# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -m rregadmin.util.glib_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.ustring_wrapper -r value_.* -r value_type_.* -r ^ValueType$ -o value_wrapper.py value_wrapper.xml'
from ctypes import *

from rregadmin.util.ustring_wrapper import gboolean
_libraries = {}
_libraries['librregadmin.so.1'] = CDLL('librregadmin.so.1')
from rregadmin.util.ustring_wrapper import guint32
from rregadmin.util.glib_wrapper import gint64
from rregadmin.util.ustring_wrapper import guint8
from rregadmin.util.glib_wrapper import gchar
STRING = c_char_p
from rregadmin.util.ustring_wrapper import UStringType
from rregadmin.util.ustring_wrapper import ustring
from rregadmin.util.ustring_wrapper import GByteArray
from rregadmin.util.glib_wrapper import GPtrArray



# values for enumeration 'ValueType'
REG_NONE = 0
REG_SZ = 1
REG_EXPAND_SZ = 2
REG_BINARY = 3
REG_DWORD = 4
REG_DWORD_LITTLE_ENDIAN = 4
REG_DWORD_BIG_ENDIAN = 5
REG_LINK = 6
REG_MULTI_SZ = 7
REG_RESOURCE_LIST = 8
REG_FULL_RESOURCE_DESCRIPTOR = 9
REG_RESOURCE_REQUIREMENTS_LIST = 10
REG_QWORD = 11
REG_QWORD_LITTLE_ENDIAN = 11
REG_MAX = 11
REG_EMPTY = 12
REG_AUTO = 13
ValueType = c_int # enum
# ../../../rregadmin/util/value.h 46
value_can_handle = _libraries['librregadmin.so.1'].value_can_handle
value_can_handle.restype = gboolean
# value_can_handle(in_type)
value_can_handle.argtypes = [ValueType]
value_can_handle.__doc__ = \
"""gboolean value_can_handle(ValueType in_type)
../../../rregadmin/util/value.h:46"""
# ../../../rregadmin/util/value.h 40
class Value_(Structure):
    pass
Value = Value_
# ../../../rregadmin/util/value.h 52
value_create_none = _libraries['librregadmin.so.1'].value_create_none
value_create_none.restype = POINTER(Value)
# value_create_none()
value_create_none.argtypes = []
value_create_none.__doc__ = \
"""Value * value_create_none()
../../../rregadmin/util/value.h:52"""
dword_type = guint32
# ../../../rregadmin/util/value.h 58
value_create_dword = _libraries['librregadmin.so.1'].value_create_dword
value_create_dword.restype = POINTER(Value)
# value_create_dword(in_int)
value_create_dword.argtypes = [dword_type]
value_create_dword.__doc__ = \
"""Value * value_create_dword(dword_type in_int)
../../../rregadmin/util/value.h:58"""
# ../../../rregadmin/util/value.h 64
value_create_dword_be = _libraries['librregadmin.so.1'].value_create_dword_be
value_create_dword_be.restype = POINTER(Value)
# value_create_dword_be(in_int)
value_create_dword_be.argtypes = [dword_type]
value_create_dword_be.__doc__ = \
"""Value * value_create_dword_be(dword_type in_int)
../../../rregadmin/util/value.h:64"""
qword_type = gint64
# ../../../rregadmin/util/value.h 70
value_create_qword = _libraries['librregadmin.so.1'].value_create_qword
value_create_qword.restype = POINTER(Value)
# value_create_qword(in_int)
value_create_qword.argtypes = [qword_type]
value_create_qword.__doc__ = \
"""Value * value_create_qword(qword_type in_int)
../../../rregadmin/util/value.h:70"""
# ../../../rregadmin/util/value.h 76
value_create_binary = _libraries['librregadmin.so.1'].value_create_binary
value_create_binary.restype = POINTER(Value)
# value_create_binary(data, data_length)
value_create_binary.argtypes = [POINTER(guint8), guint32]
value_create_binary.__doc__ = \
"""Value * value_create_binary(unknown * data, guint32 data_length)
../../../rregadmin/util/value.h:76"""
# ../../../rregadmin/util/value.h 83
value_create_from_binary = _libraries['librregadmin.so.1'].value_create_from_binary
value_create_from_binary.restype = POINTER(Value)
# value_create_from_binary(data, data_length, in_type)
value_create_from_binary.argtypes = [POINTER(guint8), guint32, ValueType]
value_create_from_binary.__doc__ = \
"""Value * value_create_from_binary(unknown * data, guint32 data_length, ValueType in_type)
../../../rregadmin/util/value.h:83"""
# ../../../rregadmin/util/value.h 92
value_create_from_string = _libraries['librregadmin.so.1'].value_create_from_string
value_create_from_string.restype = POINTER(Value)
# value_create_from_string(data, in_type)
value_create_from_string.argtypes = [STRING, ValueType]
value_create_from_string.__doc__ = \
"""Value * value_create_from_string(unknown * data, ValueType in_type)
../../../rregadmin/util/value.h:92"""
# ../../../rregadmin/util/value.h 99
value_create_string = _libraries['librregadmin.so.1'].value_create_string
value_create_string.restype = POINTER(Value)
# value_create_string(in_str, in_str_len, in_type)
value_create_string.argtypes = [STRING, guint32, UStringType]
value_create_string.__doc__ = \
"""Value * value_create_string(unknown * in_str, guint32 in_str_len, UStringType in_type)
../../../rregadmin/util/value.h:99"""
# ../../../rregadmin/util/value.h 106
value_create_expanded_string = _libraries['librregadmin.so.1'].value_create_expanded_string
value_create_expanded_string.restype = POINTER(Value)
# value_create_expanded_string(in_str, in_str_len, in_type)
value_create_expanded_string.argtypes = [STRING, guint32, UStringType]
value_create_expanded_string.__doc__ = \
"""Value * value_create_expanded_string(unknown * in_str, guint32 in_str_len, UStringType in_type)
../../../rregadmin/util/value.h:106"""
# ../../../rregadmin/util/value.h 113
value_create_multi_string_bin = _libraries['librregadmin.so.1'].value_create_multi_string_bin
value_create_multi_string_bin.restype = POINTER(Value)
# value_create_multi_string_bin(in_str, in_str_len, in_type)
value_create_multi_string_bin.argtypes = [STRING, guint32, UStringType]
value_create_multi_string_bin.__doc__ = \
"""Value * value_create_multi_string_bin(unknown * in_str, guint32 in_str_len, UStringType in_type)
../../../rregadmin/util/value.h:113"""
# ../../../rregadmin/util/value.h 121
value_create_multi_string = _libraries['librregadmin.so.1'].value_create_multi_string
value_create_multi_string.restype = POINTER(Value)
# value_create_multi_string(in_str, in_str_len, in_type)
value_create_multi_string.argtypes = [STRING, guint32, UStringType]
value_create_multi_string.__doc__ = \
"""Value * value_create_multi_string(unknown * in_str, guint32 in_str_len, UStringType in_type)
../../../rregadmin/util/value.h:121"""
# ../../../rregadmin/util/value.h 127
value_copy = _libraries['librregadmin.so.1'].value_copy
value_copy.restype = POINTER(Value)
# value_copy(in_val)
value_copy.argtypes = [POINTER(Value)]
value_copy.__doc__ = \
"""Value * value_copy(unknown * in_val)
../../../rregadmin/util/value.h:127"""
# ../../../rregadmin/util/value.h 133
value_free = _libraries['librregadmin.so.1'].value_free
value_free.restype = gboolean
# value_free(in_val)
value_free.argtypes = [POINTER(Value)]
value_free.__doc__ = \
"""gboolean value_free(Value * in_val)
../../../rregadmin/util/value.h:133"""
# ../../../rregadmin/util/value.h 139
value_equal = _libraries['librregadmin.so.1'].value_equal
value_equal.restype = gboolean
# value_equal(in_val1, in_val2)
value_equal.argtypes = [POINTER(Value), POINTER(Value)]
value_equal.__doc__ = \
"""gboolean value_equal(unknown * in_val1, unknown * in_val2)
../../../rregadmin/util/value.h:139"""
# ../../../rregadmin/util/value.h 145
value_compare = _libraries['librregadmin.so.1'].value_compare
value_compare.restype = c_int
# value_compare(in_val1, in_val2)
value_compare.argtypes = [POINTER(Value), POINTER(Value)]
value_compare.__doc__ = \
"""int value_compare(unknown * in_val1, unknown * in_val2)
../../../rregadmin/util/value.h:145"""
# ../../../rregadmin/util/value.h 154
value_is_valid = _libraries['librregadmin.so.1'].value_is_valid
value_is_valid.restype = gboolean
# value_is_valid(in_val)
value_is_valid.argtypes = [POINTER(Value)]
value_is_valid.__doc__ = \
"""gboolean value_is_valid(unknown * in_val)
../../../rregadmin/util/value.h:154"""
# ../../../rregadmin/util/value.h 160
value_is_integral_type = _libraries['librregadmin.so.1'].value_is_integral_type
value_is_integral_type.restype = gboolean
# value_is_integral_type(in_val)
value_is_integral_type.argtypes = [POINTER(Value)]
value_is_integral_type.__doc__ = \
"""gboolean value_is_integral_type(unknown * in_val)
../../../rregadmin/util/value.h:160"""
# ../../../rregadmin/util/value.h 166
value_is_string_type = _libraries['librregadmin.so.1'].value_is_string_type
value_is_string_type.restype = gboolean
# value_is_string_type(in_val)
value_is_string_type.argtypes = [POINTER(Value)]
value_is_string_type.__doc__ = \
"""gboolean value_is_string_type(unknown * in_val)
../../../rregadmin/util/value.h:166"""
# ../../../rregadmin/util/value.h 172
value_is_binary_type = _libraries['librregadmin.so.1'].value_is_binary_type
value_is_binary_type.restype = gboolean
# value_is_binary_type(in_val)
value_is_binary_type.argtypes = [POINTER(Value)]
value_is_binary_type.__doc__ = \
"""gboolean value_is_binary_type(unknown * in_val)
../../../rregadmin/util/value.h:172"""
# ../../../rregadmin/util/value.h 184
value_clear_bits = _libraries['librregadmin.so.1'].value_clear_bits
value_clear_bits.restype = gboolean
# value_clear_bits(in_val, in_bytenum, in_mask)
value_clear_bits.argtypes = [POINTER(Value), guint32, guint8]
value_clear_bits.__doc__ = \
"""gboolean value_clear_bits(Value * in_val, guint32 in_bytenum, guint8 in_mask)
../../../rregadmin/util/value.h:184"""
# ../../../rregadmin/util/value.h 196
value_set_bits = _libraries['librregadmin.so.1'].value_set_bits
value_set_bits.restype = gboolean
# value_set_bits(in_val, in_bytenum, in_mask)
value_set_bits.argtypes = [POINTER(Value), guint32, guint8]
value_set_bits.__doc__ = \
"""gboolean value_set_bits(Value * in_val, guint32 in_bytenum, guint8 in_mask)
../../../rregadmin/util/value.h:196"""
# ../../../rregadmin/util/value.h 202
value_get_raw_length = _libraries['librregadmin.so.1'].value_get_raw_length
value_get_raw_length.restype = guint32
# value_get_raw_length(in_val)
value_get_raw_length.argtypes = [POINTER(Value)]
value_get_raw_length.__doc__ = \
"""guint32 value_get_raw_length(unknown * in_val)
../../../rregadmin/util/value.h:202"""
# ../../../rregadmin/util/value.h 208
value_get_type = _libraries['librregadmin.so.1'].value_get_type
value_get_type.restype = ValueType
# value_get_type(in_val)
value_get_type.argtypes = [POINTER(Value)]
value_get_type.__doc__ = \
"""ValueType value_get_type(unknown * in_val)
../../../rregadmin/util/value.h:208"""
# ../../../rregadmin/util/value.h 214
value_get_type_str = _libraries['librregadmin.so.1'].value_get_type_str
value_get_type_str.restype = STRING
# value_get_type_str(in_val)
value_get_type_str.argtypes = [POINTER(Value)]
value_get_type_str.__doc__ = \
"""unknown * value_get_type_str(unknown * in_val)
../../../rregadmin/util/value.h:214"""
# ../../../rregadmin/util/value.h 228
value_get_as_dword = _libraries['librregadmin.so.1'].value_get_as_dword
value_get_as_dword.restype = dword_type
# value_get_as_dword(in_val)
value_get_as_dword.argtypes = [POINTER(Value)]
value_get_as_dword.__doc__ = \
"""dword_type value_get_as_dword(unknown * in_val)
../../../rregadmin/util/value.h:228"""
# ../../../rregadmin/util/value.h 238
value_get_as_qword = _libraries['librregadmin.so.1'].value_get_as_qword
value_get_as_qword.restype = qword_type
# value_get_as_qword(in_val)
value_get_as_qword.argtypes = [POINTER(Value)]
value_get_as_qword.__doc__ = \
"""qword_type value_get_as_qword(unknown * in_val)
../../../rregadmin/util/value.h:238"""
# ../../../rregadmin/util/value.h 246
value_get_as_string = _libraries['librregadmin.so.1'].value_get_as_string
value_get_as_string.restype = POINTER(ustring)
# value_get_as_string(in_val)
value_get_as_string.argtypes = [POINTER(Value)]
value_get_as_string.__doc__ = \
"""ustring * value_get_as_string(unknown * in_val)
../../../rregadmin/util/value.h:246"""
# ../../../rregadmin/util/value.h 254
value_get_as_hexstring = _libraries['librregadmin.so.1'].value_get_as_hexstring
value_get_as_hexstring.restype = POINTER(ustring)
# value_get_as_hexstring(in_val)
value_get_as_hexstring.argtypes = [POINTER(Value)]
value_get_as_hexstring.__doc__ = \
"""ustring * value_get_as_hexstring(unknown * in_val)
../../../rregadmin/util/value.h:254"""
# ../../../rregadmin/util/value.h 262
value_get_as_binary = _libraries['librregadmin.so.1'].value_get_as_binary
value_get_as_binary.restype = POINTER(guint8)
# value_get_as_binary(in_val)
value_get_as_binary.argtypes = [POINTER(Value)]
value_get_as_binary.__doc__ = \
"""guint8 * value_get_as_binary(unknown * in_val)
../../../rregadmin/util/value.h:262"""
# ../../../rregadmin/util/value.h 278
value_encode = _libraries['librregadmin.so.1'].value_encode
value_encode.restype = POINTER(GByteArray)
# value_encode(in_val, in_encode_flags)
value_encode.argtypes = [POINTER(Value), guint32]
value_encode.__doc__ = \
"""GByteArray * value_encode(unknown * in_val, guint32 in_encode_flags)
../../../rregadmin/util/value.h:278"""
# ../../../rregadmin/util/value.h 287
value_get_as_string_array = _libraries['librregadmin.so.1'].value_get_as_string_array
value_get_as_string_array.restype = POINTER(GPtrArray)
# value_get_as_string_array(in_val)
value_get_as_string_array.argtypes = [POINTER(Value)]
value_get_as_string_array.__doc__ = \
"""GPtrArray * value_get_as_string_array(unknown * in_val)
../../../rregadmin/util/value.h:287"""
# ../../../rregadmin/util/value.h 293
value_free_str_array = _libraries['librregadmin.so.1'].value_free_str_array
value_free_str_array.restype = gboolean
# value_free_str_array(in_arr)
value_free_str_array.argtypes = [POINTER(GPtrArray)]
value_free_str_array.__doc__ = \
"""gboolean value_free_str_array(GPtrArray * in_arr)
../../../rregadmin/util/value.h:293"""
# ../../../rregadmin/util/value.h 299
value_get_xml_output = _libraries['librregadmin.so.1'].value_get_xml_output
value_get_xml_output.restype = gboolean
# value_get_xml_output(in_val, in_output)
value_get_xml_output.argtypes = [POINTER(Value), POINTER(ustring)]
value_get_xml_output.__doc__ = \
"""gboolean value_get_xml_output(unknown * in_val, ustring * in_output)
../../../rregadmin/util/value.h:299"""
# ../../../rregadmin/util/value.h 305
value_debug_print = _libraries['librregadmin.so.1'].value_debug_print
value_debug_print.restype = None
# value_debug_print(in_val)
value_debug_print.argtypes = [POINTER(Value)]
value_debug_print.__doc__ = \
"""void value_debug_print(unknown * in_val)
../../../rregadmin/util/value.h:305"""
# ../../../rregadmin/util/value.h 313
value_allocated_count = _libraries['librregadmin.so.1'].value_allocated_count
value_allocated_count.restype = c_int
# value_allocated_count()
value_allocated_count.argtypes = []
value_allocated_count.__doc__ = \
"""int value_allocated_count()
../../../rregadmin/util/value.h:313"""
# ../../../rregadmin/util/value_type.h 171
value_type_from_string = _libraries['librregadmin.so.1'].value_type_from_string
value_type_from_string.restype = ValueType
# value_type_from_string(tstr)
value_type_from_string.argtypes = [STRING]
value_type_from_string.__doc__ = \
"""ValueType value_type_from_string(unknown * tstr)
../../../rregadmin/util/value_type.h:171"""
# ../../../rregadmin/util/value_type.h 179
value_type_get_string = _libraries['librregadmin.so.1'].value_type_get_string
value_type_get_string.restype = STRING
# value_type_get_string(type)
value_type_get_string.argtypes = [ValueType]
value_type_get_string.__doc__ = \
"""unknown * value_type_get_string(ValueType type)
../../../rregadmin/util/value_type.h:179"""
# ../../../rregadmin/util/value_type.h 185
value_type_get_description = _libraries['librregadmin.so.1'].value_type_get_description
value_type_get_description.restype = STRING
# value_type_get_description(type)
value_type_get_description.argtypes = [ValueType]
value_type_get_description.__doc__ = \
"""unknown * value_type_get_description(ValueType type)
../../../rregadmin/util/value_type.h:185"""
# ../../../rregadmin/util/value_type.h 191
value_type_is_valid = _libraries['librregadmin.so.1'].value_type_is_valid
value_type_is_valid.restype = gboolean
# value_type_is_valid(type)
value_type_is_valid.argtypes = [ValueType]
value_type_is_valid.__doc__ = \
"""gboolean value_type_is_valid(ValueType type)
../../../rregadmin/util/value_type.h:191"""
# ../../../rregadmin/util/value_type.h 197
value_type_is_string = _libraries['librregadmin.so.1'].value_type_is_string
value_type_is_string.restype = gboolean
# value_type_is_string(type)
value_type_is_string.argtypes = [ValueType]
value_type_is_string.__doc__ = \
"""gboolean value_type_is_string(ValueType type)
../../../rregadmin/util/value_type.h:197"""
# ../../../rregadmin/util/value_type.h 203
value_type_is_binary = _libraries['librregadmin.so.1'].value_type_is_binary
value_type_is_binary.restype = gboolean
# value_type_is_binary(type)
value_type_is_binary.argtypes = [ValueType]
value_type_is_binary.__doc__ = \
"""gboolean value_type_is_binary(ValueType type)
../../../rregadmin/util/value_type.h:203"""
# ../../../rregadmin/util/value_type.h 209
value_type_is_integral = _libraries['librregadmin.so.1'].value_type_is_integral
value_type_is_integral.restype = gboolean
# value_type_is_integral(type)
value_type_is_integral.argtypes = [ValueType]
value_type_is_integral.__doc__ = \
"""gboolean value_type_is_integral(ValueType type)
../../../rregadmin/util/value_type.h:209"""
Value_._fields_ = [
    # ../../../rregadmin/util/value.h 40
]
__all__ = ['value_create_qword', 'REG_DWORD_BIG_ENDIAN', 'REG_SZ',
           'value_encode', 'REG_BINARY', 'REG_EXPAND_SZ',
           'value_get_xml_output', 'qword_type',
           'REG_FULL_RESOURCE_DESCRIPTOR', 'value_type_is_integral',
           'value_set_bits', 'value_create_multi_string_bin',
           'value_type_get_string', 'REG_EMPTY', 'value_get_type',
           'value_type_from_string', 'value_compare', 'REG_MULTI_SZ',
           'value_create_none', 'value_type_is_valid', 'REG_LINK',
           'ValueType', 'value_create_dword_be',
           'value_is_integral_type', 'value_create_dword',
           'value_get_as_string', 'REG_QWORD', 'value_get_raw_length',
           'value_type_is_string', 'value_create_from_binary',
           'REG_AUTO', 'value_free', 'value_get_as_hexstring',
           'value_create_string', 'value_free_str_array',
           'value_copy', 'dword_type', 'REG_MAX', 'value_is_valid',
           'value_is_binary_type', 'Value', 'value_equal',
           'value_get_type_str', 'value_create_binary',
           'value_type_get_description', 'value_create_multi_string',
           'REG_QWORD_LITTLE_ENDIAN', 'REG_DWORD_LITTLE_ENDIAN',
           'value_get_as_string_array', 'value_is_string_type',
           'value_get_as_dword', 'REG_RESOURCE_REQUIREMENTS_LIST',
           'value_debug_print', 'value_get_as_binary',
           'value_create_expanded_string', 'value_type_is_binary',
           'value_allocated_count', 'REG_DWORD', 'REG_NONE',
           'value_get_as_qword', 'value_can_handle', 'Value_',
           'value_create_from_string', 'value_clear_bits',
           'REG_RESOURCE_LIST']
