# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -m rregadmin.util.glib_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_wrapper -m rregadmin.util.icu_wrapper -m rregadmin.util.path_info_wrapper -m rregadmin.util.ustring_wrapper -m rregadmin.util.offset_wrapper -m rregadmin.util.value_wrapper -m rregadmin.util.ustring_list_wrapper -m rregadmin.hive.types_wrapper -m rregadmin.registry.types_wrapper -m rregadmin.diff.diff_info_wrapper -r ^registry_diff -r ^registry_compare -r ^registry_equal -o registry_wrapper.py registry_wrapper.xml'
from ctypes import *

from rregadmin.diff.diff_info_wrapper import rra_diff_info
from rregadmin.registry.types_wrapper import Registry
_libraries = {}
_libraries['librregadmin.so.1'] = CDLL('librregadmin.so.1')
from rregadmin.diff.diff_info_wrapper import gboolean


# ../../../rregadmin/diff/registry.h 36
registry_diff = _libraries['librregadmin.so.1'].registry_diff
registry_diff.restype = POINTER(rra_diff_info)
# registry_diff(in_reg1, in_reg2)
registry_diff.argtypes = [POINTER(Registry), POINTER(Registry)]
registry_diff.__doc__ = \
"""rra_diff_info * registry_diff(unknown * in_reg1, unknown * in_reg2)
../../../rregadmin/diff/registry.h:36"""
# ../../../rregadmin/diff/registry.h 42
registry_compare = _libraries['librregadmin.so.1'].registry_compare
registry_compare.restype = c_int
# registry_compare(in_reg1, in_reg2)
registry_compare.argtypes = [POINTER(Registry), POINTER(Registry)]
registry_compare.__doc__ = \
"""int registry_compare(unknown * in_reg1, unknown * in_reg2)
../../../rregadmin/diff/registry.h:42"""
# ../../../rregadmin/diff/registry.h 48
registry_equal = _libraries['librregadmin.so.1'].registry_equal
registry_equal.restype = gboolean
# registry_equal(in_reg1, in_reg2)
registry_equal.argtypes = [POINTER(Registry), POINTER(Registry)]
registry_equal.__doc__ = \
"""gboolean registry_equal(unknown * in_reg1, unknown * in_reg2)
../../../rregadmin/diff/registry.h:48"""
__all__ = ['registry_diff', 'registry_compare', 'registry_equal']
