# generated by 'xml2py'
# flags '-c -d -v -k defst -lrregadmin -r ^rra_cli_init.*$ -o init_wrapper.py init_wrapper.xml'
from ctypes import *

_libraries = {}
_libraries['librregadmin.so.1'] = CDLL('librregadmin.so.1')


# ../../../rregadmin/cli/init.h 42
rra_cli_init = _libraries['librregadmin.so.1'].rra_cli_init
rra_cli_init.restype = None
# rra_cli_init()
rra_cli_init.argtypes = []
rra_cli_init.__doc__ = \
"""void rra_cli_init()
../../../rregadmin/cli/init.h:42"""
# ../../../rregadmin/cli/init.h 48
rra_cli_init_from_env = _libraries['librregadmin.so.1'].rra_cli_init_from_env
rra_cli_init_from_env.restype = None
# rra_cli_init_from_env()
rra_cli_init_from_env.argtypes = []
rra_cli_init_from_env.__doc__ = \
"""void rra_cli_init_from_env()
../../../rregadmin/cli/init.h:48"""
__all__ = ['rra_cli_init_from_env', 'rra_cli_init']
